version: 2

orbs:
    gcp-gke: circleci/gcp-gke@0.2.0
    gcr: circleci/gcp-gcr@0.0.2
    
jobs:
  build:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt
  test:
    docker:
      - image: circleci/python:3.7.3

    working_directory: ~/repo

    steps:
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest
 