version: 2
orbs:
    gcp-gke: circleci/gcp-gke@0.2.0
    gcr: circleci/gcp-gcr@0.0.2
    
executors:
    python3:
        docker: 
        - image: circleci/python:3.7.3
jobs:
  build:
    executor: python3
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

  test:
    executor: python3
    working_directory: ~/repo
    description: Run pytest
    steps:
      - checkout
      - run:
          name: run tests
          command: |
            . venv/bin/activate
            pytest

    #   