# General Configurations
batch_size: 50
learning_rate: 2e-4
num_epochs: 100
num_iters: 10000
is_Train:  1
grad_clip: 1
num_units: 512
embed_dim: 512
num_categories: 1354
cat_dim: 300
num_brands: 6312
brand_dim: 300
std: 0.02
restore: 0
mode: "train"
dataset: "mercari-price-prediction"

host: '0.0.0.0'
port: '5000'

train_data_path: "data/train.pickle"
val_data_path: "data/val.pickle"
brand_model_dir: "saved_models/brand_encoding.pickle"
category_model_dir: "saved_models/category_encoding.pickle"
checkpoint_dir: "saved_models/checkpoints/"